#!/bin/sh

# ARGS
FILE_PNG="$1"
RESOLUTION="$2"

if [ -z "$FILE_PNG" ];then
	echo "You need to provide a output filename!"
	exit 1
fi

# variables
FILE_RAW="$1.raw"
FOLDER_TOOLS=$(dirname $(realpath $0))
FASTBOOT="$FOLDER_TOOLS/../../out/host/fastboot/fastboot"

if [ -z "$RESOLUTION" ];then
	RESOLUTION=$($FASTBOOT getvar screen-resolution 2>&1 | head -1 | cut -d' ' -f2)
fi

# dump and convert image
$FASTBOOT dump "$FILE_RAW" oem screenshot
convert -depth 8 -size "$RESOLUTION" bgr:"$FILE_RAW" "$FILE_PNG"
rm "$FILE_RAW"
